### ISSUE TITLE
robots exclude?

### ISSUE THREAD

**Issue by evanwill** [thecdil/gayrodeo_dev#1]
@dcnb or @owikle maybe should add a robots.txt with 

```
User-agent: *
Disallow: /*
```

or to the head of every page 
`<meta name="robots" content="noindex" />`

to avoid this getting indexed

**Comment by dcnb** [comment]
Already there, @evanwill! 

@owikle is way ahead of you.

**Comment by evanwill** [comment]
Not *way* ahead exactly :wink: 
Guess I was thinking just like @owikle !
